# Generated by Django 4.0.4 on 2022-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, verbose_name='Наименование')),
                ('slider', models.ImageField(default='default.jpg', upload_to='slider')),
                ('is_show', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
