# Generated by Django 4.0.4 on 2022-06-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_cupon_order_product_price_productinorder_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='img',
        ),
    ]
