# Generated by Django 4.0.4 on 2022-08-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baguette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('color', models.CharField(max_length=64, verbose_name='Цвет')),
                ('material', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Материал')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Багет',
                'verbose_name_plural': 'Багеты',
            },
        ),
        migrations.CreateModel(
            name='BaguetteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет багета',
                'verbose_name_plural': 'Цвета багета',
            },
        ),
        migrations.CreateModel(
            name='BaguetteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=64, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал багета',
                'verbose_name_plural': 'Материалы багета',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64, verbose_name='Страна-производитель')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('thread', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Вид ниток')),
                ('material', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Материал')),
                ('length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, verbose_name='Длина мотка')),
                ('themes', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Тематика')),
                ('technique', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Техника')),
                ('stitching', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Зашивка')),
                ('dimension', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Размер')),
                ('purpose', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Назначение')),
                ('equipment', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Комплектация')),
                ('num_color', models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество цветов')),
                ('num_bead', models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество бусин')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.country')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textile', models.CharField(max_length=64, verbose_name='Вид ткани')),
            ],
            options={
                'verbose_name': 'Вид ткани',
                'verbose_name_plural': 'Виды ткани',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default.jpg', upload_to='products_images')),
                ('picture_small', models.ImageField(default='products_images_small/default.jpg', upload_to='products_images_small')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='textile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.textile'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type'),
        ),
    ]
