# Generated by Django 4.0.4 on 2022-08-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baguette',
            name='color',
        ),
        migrations.RemoveField(
            model_name='baguette',
            name='material',
        ),
    ]
