# Generated by Django 4.0.4 on 2022-08-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_baguette_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='baguette',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.baguettecolor'),
        ),
    ]
