# Generated by Django 4.0.4 on 2022-04-21 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_color_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='equipment',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Комплектация'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, verbose_name='Длина мотка'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='num_bead',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество бусин'),
        ),
        migrations.AddField(
            model_name='product',
            name='num_color',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество цветов'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='product',
            name='stitching',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Зашивка'),
        ),
        migrations.AddField(
            model_name='product',
            name='technique',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='product',
            name='themes',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='product',
            name='thread',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Вид ниток'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
