# Generated by Django 4.0.4 on 2022-06-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='picture_small',
            field=models.ImageField(default='default.jpg', upload_to='products_images_small'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='products_images'),
        ),
    ]
