# Generated by Django 4.0.4 on 2022-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_new_productimage_picture_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='picture_small',
            field=models.ImageField(default='products_images_small/default.jpg', upload_to='products_images_small'),
        ),
    ]
